config/routes.rb
GalleryScrape::Application.routes.draw do
  get "gallery/index"
  resources :gallery, :scrape_imgs

    match 'gallery/show' => 'gallery#show'
    match 'seotest/index' => 'seotest#index'

   root :to => 'gallery#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	require 'open-uri'
	require 'nokogiri'

	def index

	end

	def show
		@orientation = params[:Horizontal]
		@largesize = params[:LargeImages]
		arr = params[:CTYHOCN].split("\r\n")
		scrape_imgs(arr)
	end

	def scrape_imgs(arr)
		@img_urls = Array.new
		@img_captions = Array.new
		@img_alts = Array.new
		@table_hsh = Array.new

		arr.each do |ctyhocn|
			url = "http://www3.hilton.com/en/hotels/united-kingdom/" + ctyhocn + "/index.html"

			doc = Nokogiri::HTML(open(url))
			@img_urls = doc.css('.gallery img').map{ |i| i['src'] } # array of image urls [url1, url2, url3]
			@large_img_urls = doc.css('.gallery .img').map{ |url| url }
			@img_captions = doc.css('.gallery .title').map{ |alt| alt} 
			@img_alts = doc.css('.gallery .image_alt').map{ |alt| alt } # array of image captions [caption1, caption2, caption 3]
			@table_hsh << {:ctyhocn => ctyhocn, :imgs => @img_urls, :captions => @img_captions, :large_img_urls => @large_img_urls, :alt_text => @img_alts }
			#@img_captions = @doc.css('.gallery .image_alt').map{ |alt| alt }
		end

		@table_hsh

	end
end

app/controllers/seotest_controller.rb
class SeotestController < ApplicationController
	def index
		render :layout => false
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/seotest_helper.rb
module SeotestHelper
end

app/views/gallery/index.html.erb
<div class="container" align="center">
<%= form_tag "/gallery/show/", :method => 'post' do %>
<div class="row">
	<div class="jumbotron">
		<h1>Image Gallery Scraper</h1>
		<p>Enter CTYHOCNs in the text box below to scrape the images, descriptions and URLs.  These can be easily pasted into Excel for further editing.</p>
		
	</div>
	<p>More than one CTYHOCN can be entered, however, if the request takes too long the server will time out.  Try to keep it to just a couple of hotels at a time to reduce frustrations.</p>
		<p>Enjoy!</p>
</div>
<table>
	<tr><td><strong>CTYHOCNS <small><em>(1 per line)</em></small></strong></td></tr>
  <tr><Td><%= text_area_tag "CTYHOCN", nil, rows: 10, :placeholder => "LHRHITW\nLONHITW" %></td></tr>
 </td></tr>
   <tr><td> <%= check_box_tag 'Horizontal', 'Yes' %> Horizontal Orientation</td></tr>
  <tr><td> <%= check_box_tag 'LargeImages', 'Yes' %> Large Images</td></tr>
  <tr><td>&nbsp;</td></tr>
  <tr><Td><%= submit_tag "Get Gallery Images", :class=>"btn btn-primary" %></td></tr>


 </table>
<% end %>
<div>
	<br><br><br>
	<p>As time goes on, the brand.com HTML that this tool is dependent on may change.  If you would like to make updates or change this tool, feel free to contribute to it (<a href="https://github.com/jerednel/galleryscrape">Github</a>).</p>
</div>
</div>

app/views/gallery/show.html.erb

<% img_size = 1 %>
<% if @largesize.nil? %>
<% img_size = 0 %>
<% end %>

<% if @orientation.nil? %>


<table class="table table-hover">
	<strong><tr><th>CTYHOCN</th><th>Thumbnail</th><th>Caption</th><th>Image URL</th><th>ALT Text</th></tr></strong>
	<% @table_hsh.each do |row| %>
	  <% i = 0 %>

	  <% if img_size == 0 %> 
	    <% row[:imgs].each do |img_url| %>
	    <tr>
	    	<td><%= row[:ctyhocn] %></td><td><img src="http://www3.hilton.com<%=img_url %>"></td>
	    	<td><%= row[:captions][i].to_s.gsub!('<span class="title">', '').gsub!('</span>', '')  %></td>
	    	<td>http://www3.hilton.com<%=img_url %></td>
	    	<td><%= row[:alt_text][i].to_s.gsub!('<span class="image_alt">', '').gsub!('</span>', '')   %></td>
	    </tr>
	    <% i = i + 1 %>
	  <% end %>	    
	  <% else %>
	    <% row[:large_img_urls].each do |img_url| %>
	    <tr>
	    	<td><%= row[:ctyhocn] %></td><td><img src="http://www3.hilton.com<%= img_url.to_s.gsub!('<span class="img">', '').gsub!('</span>', '') %>"></td>
	    	<td><%= row[:captions][i].to_s.gsub!('<span class="title">', '').gsub!('</span>', '')  %></td>
	    	<td>http://www3.hilton.com<%= img_url.to_s.gsub!('<span class="img">', '').gsub!('</span>', '') %></td>
	    	<td><%= row[:alt_text][i].to_s.gsub!('<span class="image_alt">', '').gsub!('</span>', '')  %></td>
	    </tr>
	    <% i = i + 1 %>
	  <% end %>	    
	  <% end %>

	<% end %>
</table>

<% else %>
<table>

		<tr>
	<% @table_hsh.each do |row| %>
	  <% i = 0 %>
	  <% if img_size == 0 %> 
	  <% row[:imgs].each do |img_url| %>
	    	<td>http://www3.hilton.com<%=img_url %></td>
	    <% i = i + 1 %>
	  <% end %>

	  <% else %> 
		<% row[:large_img_urls].each do |img_url| %>
	    	<td>http://www3.hilton.com<%= img_url.to_s.gsub!('<span class="img">', '').gsub!('</span>', '') %></td>
	    <% i = i + 1 %>
	  <% end %>

	  <% end %>
	<% end %>
	</tr>

		<tr>
	<% @table_hsh.each do |row| %>
	  <% i = 0 %>
	  <% row[:imgs].each do |img_url| %>
	    	<td><%= row[:captions][i].to_s.gsub!('<span class="title">', '').gsub!('</span>', '')  %></td>
	    <% i = i + 1 %>
	  <% end %>
	<% end %>
	</tr>


	<tr>
	<% @table_hsh.each do |row| %>
	  <% i = 0 %>

	  <% if img_size == 0 %> 
	  <% row[:imgs].each do |img_url| %>
	    	<td><img src="http://www3.hilton.com<%=img_url %>"></td>
	    <% i = i + 1 %>
	  <% end %>
	  <% else %>
		<% row[:large_img_urls].each do |img_url| %>
	    	<td><img src="http://www3.hilton.com<%= img_url.to_s.gsub!('<span class="img">', '').gsub!('</span>', '') %>"></td>
	    <% i = i + 1 %>
	  <% end %>
	  <% end %>

	<% end %>


	<tr>
	<% @table_hsh.each do |row| %>
	  <% i = 0 %>
	  <% row[:imgs].each do |img_url| %>
	    	<td><%= row[:ctyhocn] %></td>
	    <% i = i + 1 %>
	  <% end %>
	<% end %>
	</tr>
	</tr>






	
	    	
</table>

<% end %>

app/views/gallery/show_old.html.erb


<table>
	<% @table_hsh.each do |row| %>
	  <% i = 0 %>
	  <% row[:imgs].each do |img_url| %>
	    <tr>
	    	<td><%= row[:ctyhocn] %></td><td><img src="http://www3.hilton.com<%=img_url %>"></td>
	    	<td><%= row[:captions][i].to_s.gsub!('<span class="title">', '').gsub!('</span>', '')  %></td>
	    	<td>http://www3.hilton.com<%=img_url %></td>
	    </tr>
	    <% i = i + 1 %>
	  <% end %>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
</head>
<body>

<%= yield %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-7955878-30', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/seotest/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Google Search Limit Testing Page for SEO Purposes, T1 - ijelmrdk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>
<body>

<h1>Meta Title Testing Page</h1>
	<p>The string at the end of the page title is a word that has 0 search results in Google.  It is the only mention of it anywhere on this page.  If Google indexes the page for that phrase, then we can conclude that phrases up to at least 65 characters are still considered in indexing and ranking.</p>

</body>
</html>